# Generated by Django 4.1.2 on 2022-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0011_activitytype_thematicmember_thematic_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('part_id', models.CharField(max_length=200, verbose_name='id')),
                ('organization', models.CharField(max_length=200, verbose_name='organization')),
                ('organization_type', models.CharField(max_length=200, verbose_name='Organization_type')),
                ('activity_id', models.CharField(max_length=200, verbose_name='activity_identity')),
            ],
        ),
    ]
