# Generated by Django 4.1.2 on 2022-10-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0012_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='organization_type',
        ),
    ]
