# Generated by Django 4.1.2 on 2022-10-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0013_remove_participant_organization_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='part_id',
        ),
        migrations.AddField(
            model_name='participant',
            name='activity_county',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='activity_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='activity_subcounty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='activity_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='actual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='participant',
            name='budget',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='participant',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='donor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Donor/Sponsered'),
        ),
        migrations.AddField(
            model_name='participant',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='participant',
            name='end_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='participant',
            name='groups',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Groups/Stakeholders'),
        ),
        migrations.AddField(
            model_name='participant',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='participant',
            name='organizer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='proffesion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proffesion'),
        ),
        migrations.AddField(
            model_name='participant',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='participant',
            name='start_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='subcounty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcounty'),
        ),
        migrations.AddField(
            model_name='participant',
            name='thematic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Thematic'),
        ),
        migrations.AddField(
            model_name='participant',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='participant',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
    ]
